config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  devise_for :users
  root to: "pages#home"

  resources :videos

  resources :posts do

    member do
      post 'favorite'
      delete 'unfavorite'
    end

    resources :chatrooms do
      resources :messages, only: [:create, :destroy]
    end

    resources :treasures, only: [:new, :create, :edit, :update] do
      # put :update_status, on: :member


      put :mark_as_pending, on: :member, action: :mark_as_pending
      put :mark_as_collected, on: :member, action: :mark_as_collected
      put :mark_as_available, on: :member, action: :mark_as_available


      member do
        delete 'delete'
      end
    end
  end



# Define the route for the dashboard
get '/dashboard', to: 'dashboard#show', as: :dashboard



end

app/controllers/concerns/dashboard_controller.rb
class DashboardController < ApplicationController
  def show






    @user = current_user
    @posts = @user.posts
    @favorite_posts = current_user.favorited_posts
    @collected_treasures =  current_user.treasures.collected

    @markers = @favorite_posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { post: post })
      }
    end

  end








end

app/views/dashboard/_favourites.html.erb
<div class="row">
<div class="col-md-6">
  <h3 class="mb-4">Your 'pick' list</h3>
  <% @favorite_posts.each do |post| %>
      <div class="favorite-post mb-3">
        <h6 class="mb-2">
        <%= link_to post.location, post_path(post), class: "custom-link" %>
        </h6>

          <% post.treasures.each do |treasure| %>
          <% unless current_user.treasures.collected.include?(treasure) %>
          <div class="row mb-1 treasure-item align-items-center">
              <div class="col-md-6">
                  <strong>Item:</strong> <%= treasure.description %>
              </div>
              <div class="col-md-5 text-right">
                  <% if treasure.available? %>
                  <%= button_to "Click when collected", mark_as_pending_post_treasure_path(post, treasure), method: :put, class: 'btn btn-success btn-sm' %>
                  <% elsif treasure.collected? %>
                  <%= button_to "Item is no longer available", '#', disabled: true, class: 'btn btn-outline-danger btn-sm' %>
                  <% elsif treasure.pending? %>
                  <%= button_to "Owner has been notified", '#', disabled: true, class: 'btn btn-outline-info btn-sm' %>
                  <% end %>
              </div>
          </div>
            <hr>
          <% end %>
          <% end %>
      </div>
  <% end %>
</div>

app/views/dashboard/_map.html.erb
<div class="col-md-6">
    <%# <h3 class="mb-4" style="text-decoration: none; color: black;"></h3> %>
    <div style="width: 100%;">
        <div data-controller="map"
             data-map-markers-value="<%= @markers.to_json %>"
             data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
             style="height: 500px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);"></div>
    </div>
</div>

app/views/dashboard/_your_hard_rubbish.html.erb
<h3 class="mb-4">Your hard rubbish posts</h3>

<% if current_user.posts.present? %>
    <% current_user.posts.each do |post| %>
        <div class="favorite-post mb-4">
            <div class="row align-items-center mb-2">
                <!-- Location Column -->
                <div class="col-md-4">
                    <h6 class="mb-2">
                        <%= link_to post.location, post_path(post), class: "custom-link" %>
                    </h6>
                </div>

                <!-- Favorites Column -->
                  <div class="col-md-6">
                      <h6 class="d-inline-block mb-0"><%= post.favoritors.size %></h6>

                      <% if post.favoritors.size == 0 %>
                          <span class="ml-2">pickers</span>
                      <% elsif post.favoritors.size == 1 %>
                          <span class="ml-2">picker</span>
                      <% else %>
                          <span class="ml-2">pickers</span>
                      <% end %>

                      <i class="fa-solid fa-heart fa-lg d-inline-block ml-2" style="color: #FFBB02;"></i>
                      <span class="ml-2"> your rubbish</span>
                  </div>


            <!-- Treasures Section -->
            <% post.treasures.each do |treasure| %>
                <div class="row mb-2 treasure-item align-items-center">
                    <!-- Description Column -->
                    <div class="col-md-6">
                        <strong>Item:</strong> <%= treasure.description %>
                        <% if treasure.pending? %>
                        <div class="d-flex mt-1">
                          <%= button_to "Yes, item has been collected", mark_as_collected_post_treasure_path(post, treasure), method: "put", class: 'btn btn-outline-danger btn-sm' %>
                            <div style= "width: 20px; display: inline-block;"></div>
                          <%= button_to "No, item is still available", mark_as_available_post_treasure_path(post, treasure), method: "put", class: 'btn btn-outline-info btn-sm' %>
                        </div>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <hr>
    <% end %>
<% else %>
    <p>You haven't uploaded any hard rubbish to Kerbside.</p>
<% end %>

app/views/dashboard/_your_treasures.html.erb
<%# <h3 class="mb-4">The hard rubbish you've saved from landfill</h3>

<% if @collected_treasures.empty? %>
    <%# <p>Nothing (yet). Today is a good day to start picking</p>
<% else %>
    <%# <% @collected_treasures.each do |treasure| %>
            <%# <%= treasure.description
            <%= treasure.treasure_type
            <% video = Video.find(treasure.treasure_type.video_id) %>
            <%# <%= video.url

            <%= link_to video_path(video), class: 'text-decoration-none text-dark' do %>
                <%# <div class="card h-100">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="<%= video.url %>
                        <%# " frameborder="0" allowfullscreen></iframe> %>
                    <%# </div>
                    <div class="card-body">
                        <h5 class="card-title"><strong><%= video.title %>
                        <%# </strong></h5> %>
                    <%# </div>
                </div>
            <% end %>
        <%# </div>
    <% end %>
<%# <% end %>
<%# </div> %>

<h3 class="mb-4">Your 'picks' and matching DIY videos</h3>

<% if @collected_treasures.empty? %>
    <p>Nothing (yet). Today is a good day to start picking</p>
<% else %>
    <% @collected_treasures.each do |treasure| %>
        <strong>Item:</strong> <%= treasure.description %>

        <% video = Video.find(treasure.treasure_type.video_id) %>

        <div class="embed-responsive embed-responsive-16by9 mt-3">
            <iframe class="embed-responsive-item" src="<%= video.url %>" frameborder="0" allowfullscreen></iframe>
        </div>
        <h5 class="card-title"><strong><%= video.title %></strong></h5>
    <% end %>
<% end %>
</div>

app/views/dashboard/show.html.erb
<div class="container mt-5" style="margin-bottom: 60px;">
    <h2 class="mb-3">Dashboard: <%= @user.first_name %> <%= @user.last_name %></h2>

  <hr>


  <div class="row mb-4">
      <div class="col-md-12">
          <div class="card no-outline-shadow-card_ok mb-0">
              <div class="card-body">
                  <!-- Your Favorites Section -->
                  <%= render 'favourites' %>
                  <!-- Map Section -->
                   <%= render 'map' %>
              </div>
          </div>
        </div>
      </div>
  </div>


          <!-- Your hard rubbish -->
  <div class="card no-outline-shadow-card_ok mb-4">
    <div class="card-body">
      <%= render 'your_hard_rubbish' %>

         <!-- Your Treasures Section -->
        <%= render 'your_treasures' %>
    </div>
  </div>
</div>