config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  devise_for :users
  root to: "pages#home"

  resources :videos

  resources :posts do

    member do
      post 'favorite'
      delete 'unfavorite'
    end

    resources :chatrooms do
      resources :messages, only: [:create, :destroy]
    end

    resources :treasures, only: [:new, :create, :edit, :update] do
      # put :update_status, on: :member


      put :mark_as_pending, on: :member, action: :mark_as_pending
      put :mark_as_collected, on: :member, action: :mark_as_collected
      put :mark_as_available, on: :member, action: :mark_as_available


      member do
        delete 'delete'
      end
    end
  end



# Define the route for the dashboard
get '/dashboard', to: 'dashboard#show', as: :dashboard



end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    <strong>Kerbside - Helping people find the treasure in your trash.</strong>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to posts_path, class: "navbar-brand" do %>
      <%= image_tag "Kerbside logo.png", style: "width: 180px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
         <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", posts_path, class: "nav-link" %>
          </li>
            <li class="nav-item">
            <%= link_to "Post", new_post_path, class: "nav-link" %>
          </li>
</li>
            <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>


          <li class="nav-item">
            <%= link_to "Videos", videos_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
         <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn-ghost" %>
          </li>
          <li class="nav-item dropdown">
            <%# <%=class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
              <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
       <% end %>
      </ul>
    </div>
  </div>
</div>