config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  devise_for :users
  root to: "pages#home"

  resources :videos

  resources :posts do

    member do
      post 'favorite'
      delete 'unfavorite'
    end

    resources :chatrooms do
      resources :messages, only: [:create, :destroy]
    end

    resources :treasures, only: [:new, :create, :edit, :update] do
      # put :update_status, on: :member


      put :mark_as_pending, on: :member, action: :mark_as_pending
      put :mark_as_collected, on: :member, action: :mark_as_collected
      put :mark_as_available, on: :member, action: :mark_as_available


      member do
        delete 'delete'
      end
    end
  end



# Define the route for the dashboard
get '/dashboard', to: 'dashboard#show', as: :dashboard



end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :treasures, dependent: :destroy
  validates :location, presence: true
  has_one :chatroom, dependent: :destroy
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode    #, if: :will_save_change_to_location?


  acts_as_favoritable






end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



  def index

    if params[:query].present?
      sql_subquery = <<~SQL
        posts.location ILIKE :query
        OR posts.description ILIKE :query
        OR posts.council_pickup_date::TEXT LIKE :query
      SQL

      @posts = Post.where(sql_subquery, query: "%#{params[:query]}%")
      @markers = @posts.geocoded.map do |post|
        {
          lat: post.latitude,
          lng: post.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: {post: post})
        }
      end

    else

    @posts = Post.all

    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {post: post})
      }
    end
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @chatroom = Chatroom.new
    @chatroom.post_id = @post.id
    @chatroom.name = "chatroom for #{@post.description}"
    @post.chatroom = @chatroom
    @chatroom.save

    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def favorite
    @post = Post.find(params[:id])
    current_user.favorite(@post)

    if request.referer.include?(request.path_parameters[:id])

      redirect_to post_path, notice: 'Post favorited!'
    else

      redirect_to posts_path, notice: 'Post favorited!'
    end

  end


 def unfavorite
  @post = Post.find(params[:id])
  current_user.unfavorite(@post)

  if request.referer.include?('dashboard') # check if current page is dashboard
    redirect_to dashboard_path, notice: 'Post unfavorited!'
  elsif request.referer.include?(request.path_parameters[:id]) # check if current page is post/:id
    redirect_to post_path, notice: 'Post unfavorited!'
  else # assume current page is post index
    redirect_to posts_path, notice: 'Post unfavorited!'
  end
end

  def favorites
    @favorite_posts = current_user.favorited_posts
  end

  def show
    @post = Post.find(params[:id])
    @chatroom = @post.chatroom
    @message = Message.new
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Hard rubbish listing updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])

    unless @post.user == current_user
      flash[:alert] = "You are not allowed to delete this post. For more information contact admin@admin.nz"
      redirect_to @post and return
    end

    if @post.destroy
      redirect_to posts_path, notice: "Hard rubbish listing deleted successfully."
    else
      flash[:alert] = "Failed to delete hard rubbish listing."
      redirect_to @post
    end
  end

  private

    def post_params
      params.require(:post).permit(:location, :description, :council_pickup_date, photos: [])
    end
end

app/views/posts/_info_window.html.erb
<div class="oval-card" style="background-image: linear-gradient(rgba(0,0,0,0.3),
 rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/
 <%= post.description%>');" data-post-id="<%= post.id %>">

<p style="font-weight: bold;"><%= post.location %></p>
<p><%= post.description %></p>

</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-6 form-login">
          <h2>Edit a Post</h2>
          <%= form_with(model: @post, local: true, html: { enctype: "multipart/form-data" }) do |form| %>

            <div class="form-group">
              <%= form.label :location, "Location" %>
              <%= form.text_field :location, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= form.label :description, "Description" %>
              <%= form.text_area :description, class: "form-control", rows: 3, required: true %>
            </div>

            <div class="form-group">
              <%= form.label :council_pickup_date, "Council Pickup Date" %>
              <%= form.date_field :council_pickup_date, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= form.label :photos, "Photos" %>
              <%= form.file_field :photos, class: "form-control-file", multiple: true %>
            </div>

            <%= form.submit "Update", class: "btn btn-primary mt-2" %>
          <% end %>
      </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-4">
  <h1 class="mb-3">All Posts</h1>


    <hr>

<div class="row align-items-center mb-3">
    <!-- search bar -->
    <div class="col-md-8">
        <%= form_with url: posts_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query, params[:query], class: "form-control", style: "width: 70%;", placeholder: "Search by location, item or days to council pickup" %>
        <% end %>
    </div>

  <!--"Add New Post" button -->
    <div class="col-md-4 text-end">
      <%= link_to 'Add New Post', new_post_path, class: "btn btn-flat" %>
    </div>
    </div>


  <div class="row">

    <!-- Posts Column -->
    <div class="col-md-8">
      <div class="row row-cols-1 row-cols-md-4 g-4">
        <% @posts.each do |post| %>
          <div class="col">
            <%= link_to post_path(post), class: 'text-decoration-none text-dark' do %>
              <div class="card outline-card fixed-height-card">
                <% if post.photos.attached? %>
                  <div class="card-img-index position-relative">
                    <% post.photos.each do |image| %>
                      <%= cl_image_tag image.key, class: "img-fluid uniform_image_card", style: "width: 100%;" %>
                    <% end %>
                  </div>
                <% else %>
                  <p>No photos available.</p>
                <% end %>

                  <div class="card-body" style="min-height: 200px;">
                        <h6 class="card-title"><strong><%= post.location %></strong></h6>

                        <% if post.description.length > 60 %>
                            <p class="card-text"><%= "#{post.description[0..59]}..." %></p>
                        <% else %>
                            <p class="card-text"><%= post.description %></p>
                        <% end %>


                  <!-- Council Pickup Positioning -->
                        <div class="position-absolute bottom-0 start-1 p-1">
                          <% if post.council_pickup_date? %>
                            <p class="card-text" style="font-size: 0.9em;">
                              <% days_remaining = (post.council_pickup_date - Date.today).to_i %>
                              <% if days_remaining <= 5 %>
                                <strong style="color: #FF5C5C;"><%= pluralize(days_remaining, 'day') %></strong> till council pickup
                              <% else %>
                                <strong style="color: black;"><%= pluralize(days_remaining, 'day') %></strong> till council pickup
                              <% end %>
                            </p>
                          <% else %>
                            <p>No council pickup date available.</p>
                          <% end %>
                        </div>


                  <!-- Heart Icon Positioning -->
                <div class="position-absolute top-0 end-0 p-2" >
                    <% if current_user.favorited?(post) %>
                      <%= link_to unfavorite_post_path(post), data: {turbo_method: :delete} do %>
                        <i class="fa-solid fa-heart fa-lg"></i>
                      <% end %>
                    <% else %>
                      <%= link_to favorite_post_path(post), data: {turbo_method: :post} do %>
                        <i class="fa-regular fa-heart"></i>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

<!-- Map box Positioning -->

    <div class="col-md-4 map-container sticky-map">
      <div style="width: 100%; height: 1150px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= simple_form_for(Post.new, data: { controller: "sweet-alert", action: "submit->sweet-alert#confirmSubmit" }) do |form| %>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 form-login">
          <h1>Post hard rubbish</h1>

          <%= form.error_notification %>
          <div class="form-inputs">
            <%= form.input :location, required: true %>
            <%= form.input :description, required: true, input_html: { rows: 3 } %>
            <%= form.input :council_pickup_date, required: true, as: :date %>
            <%= form.input :photos, as: :file, input_html: { multiple: true } %>
          </div>
          <div class="form-actions">
            <%= form.button :submit, "Submit", class: "btn btn-primary" %>
          </div>

      </div>
    </div>
  </div>

<% end %>

app/views/posts/show.html.erb
<div class="container mt-5">
<h2 class="mb-4">Hard rubbish details: <%= @post.location %></h2>
  <div class="row">
    <div class="col-md-8">

      <!-- Post Section -->
        <div class="card no-outline-shadow-card_ok mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4 position-relative">
                        <% if @post.photos.attached? %>
                            <% @post.photos.each do |image| %>
                                <%= cl_image_tag image.key, height: 200, width: 200, crop: :fill, class: "show_image_card " %>
                            <% end %>

                            <div class="position-absolute top-0 start-1 p-2">
                                <% if current_user.favorited?(@post) %>
                                    <%= link_to unfavorite_post_path(@post), data: {turbo_method: :delete} do %>
                                        <i class="fa-solid fa-heart fa-lg"></i>
                                    <% end %>
                                <% else %>
                                    <%= link_to favorite_post_path(@post), data: {turbo_method: :post} do %>
                                        <i class="fa-regular fa-heart"></i>
                                    <% end %>
                                <% end %>
                            </div>

                        <% else %>
                            <p class="text-muted">No photos uploaded.</p>
                        <% end %>

                        <% if @post.user == current_user %>
                            <%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-outline-secondary btn-sm mt-2" %>
                            <%= link_to post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Delete #{@post.description}?" }, class: "btn btn-outline-danger btn-sm mt-2" do %> Delete Post <% end %>
                        <% end %>
                    </div>
                    <div class="col-md-8">
                        <p><strong>Description:</strong> <%= @post.description %></p>
                        <p><strong>Council pickup date:</strong> <%= @post.council_pickup_date %></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Treasures Section -->
        <div class="card no-outline-shadow-card_ok mb-5">
            <div class="card-body">
              <h4>Individual items</h4>
              <div class="treasures">
                <% if @post.treasures.any? %>
                  <% @post.treasures.each do |treasure| %>
                    <div class="row mb-1 treasure-item" id="treasure-item-<%= treasure.id %>">
                      <div class="col-md-4">
                        <% if treasure.photo.attached? %>
                          <%= cl_image_tag treasure.photo.key, height: 200, width: 200, crop: :fill, class: "show_image_card" %>
                        <% end %>
                          <% if @post.user == current_user %>
                            <%= link_to delete_post_treasure_path(@post, treasure), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "btn btn-outline-danger btn-sm" do %> Delete item<% end %>
                          <% end %>
                      </div>
                      <div class="col-md-8">
                      <p><strong>Type:</strong> <%= treasure.treasure_type.category%></p>
                        <p><strong>Description:</strong> <%= treasure.description %></p>
                        <p><strong>Status:</strong> <%= treasure.status ? "Available" : "Not Available" %></p>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <div class="col">
                    <p class="text-muted">No information for the individual items has been added.</p>
                  </div>
                <% end %>
              </div>
              <% if @post.user == current_user %>
                <%= link_to 'Add item', new_post_treasure_path(@post), class: "btn btn-primary btn-sm" %>
              <% end %>
            </div>
          </div>
        </div>

          <!-- Chatroom section -->
          <div class="col-md-4">
              <div class="card" style="border-radius: 15px;">
                  <div class="card-body">
                      <!-- Render the chatroom content -->
                      <%= render "chatrooms/chatroom", chatroom: @post.chatroom, current_user: current_user %>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <script>
    document.addEventListener('ajax:success', function(event) {
      if (event.target.matches('.btn-danger')) {
        var treasureId = event.detail[0].id;
        document.getElementById('treasure-item-' + treasureId).remove();
      }
    });
  </script>
</div>