config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  devise_for :users
  root to: "pages#home"

  resources :videos

  resources :posts do

    member do
      post 'favorite'
      delete 'unfavorite'
    end

    resources :chatrooms do
      resources :messages, only: [:create, :destroy]
    end

    resources :treasures, only: [:new, :create, :edit, :update] do
      # put :update_status, on: :member


      put :mark_as_pending, on: :member, action: :mark_as_pending
      put :mark_as_collected, on: :member, action: :mark_as_collected
      put :mark_as_available, on: :member, action: :mark_as_available


      member do
        delete 'delete'
      end
    end
  end



# Define the route for the dashboard
get '/dashboard', to: 'dashboard#show', as: :dashboard



end

app/models/treasure.rb
class Treasure < ApplicationRecord
  enum status: {
    available: 0,
    collected: 1,
    pending: 2
  }


  belongs_to :treasure_type
  belongs_to :post

  has_one_attached :photo

  # validates :status, inclusion: { in: [true, false] }


end

app/models/treasure_type.rb
class TreasureType< ApplicationRecord
  has_many :videos
  has_many :treasures

end

app/models/treasuretype.rb
class TreasureType< ApplicationRecord
  belongs_to :video
end

app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController
  before_action :set_post
  before_action :set_treasure, only: [:edit, :update]



  # def update_status
  #   @treasure = Treasure.find(params[:id])
  #   @treasure.update(status: !@treasure.status)
  #   redirect_to dashboard_path # Redirect to the appropriate path after updating
  # end



  def mark_as_pending
    treasure = Treasure.find(params[:id])
    treasure.update(status: :pending)
    redirect_to dashboard_path, notice: "Treasure marked as pending."
  end

  def mark_as_collected
    treasure = Treasure.find(params[:id])
    treasure.update(status: :collected)
    redirect_to dashboard_path, notice: "Treasure marked as collected."
  end

  def mark_as_available
    treasure = Treasure.find(params[:id])
    treasure.update(status: :available)
    redirect_to dashboard_path, notice: "Treasure marked as available."
  end



  def new
    @treasure = @post.treasures.build
  end

  def create
    @treasure = @post.treasures.build(treasure_params)
    @treasure.status = :available

    if @treasure.save
      redirect_to @post, notice: 'Treasure was successfully added.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @treasure.update(treasure_params)
      redirect_to @post, notice: 'Treasure was successfully updated.'
    else
      render :edit
    end
  end

  def delete
    @treasure = Treasure.find(params[:id])
    @treasure.destroy

    respond_to do |format|
      format.js
    end
  end



  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_treasure
    @treasure = @post.treasures.find(params[:id])
  end

  def treasure_params
    params.require(:treasure).permit(:description, :treasure_type_id, :photo, :status)
  end
end

app/views/treasures/delete.js.erb
document.getElementById('treasure-item-' + <%= @treasure.id %>).remove();

app/views/treasures/edit.html.erb
<div class="container">
  <h3>Edit Treasure</h3>
  <%= simple_form_for [@post, @treasure], url: post_treasure_path(@post, @treasure), method: :patch do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.association :treasure_type, label: "Treasure Type", collection: TreasureType.all, value_method: :id, label_method: :category, prompt: "Select a type" %>
      <%= f.input :description, label: "Description" %>
      <%= f.input :photo, label: "Include a photo", as: :file %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Update Treasure", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/treasures/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 form-login">
      <h3 class="mb-3">Add individual rubbish items</h3>
      <%= simple_form_for [@post, @treasure], url: post_treasures_path(@post) do |f| %>
       <%= f.error_notification %>
        <div class="form-inputs mb-3">
          <%= f.association :treasure_type, label: "Treasure Type", collection: TreasureType.all, value_method: :id, label_method: :category, prompt: "Select a type", input_html: { class: "form-control" } %>
          <%= f.input :description, label: "Description" %>
          <%= f.input :photo, label: "Include a photo", as: :file %>
        </div>
        <div class="form-actions">
        <%= f.button :submit, "Add Treasures", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>